import { KnowledgePack, SchematicGeometry } from '@neuroatlas/schemas';

/**
 * Paquete mínimo y válido para pruebas. Los datos son ficticios a propósito
 * (especies "Testus a/b"): solo prueban reglas, no contenido científico.
 */
export function makeFixturePack(): KnowledgePack {
  return KnowledgePack.parse({
    schemaVersion: '1',
    release: {
      id: '2026.10.0-test',
      channel: 'dev',
      cutoffDate: '2026-10-04',
      notes: { es: 'test' },
    },
    sources: [
      {
        id: 'src.test',
        type: 'article',
        title: 'Fuente de prueba',
        year: 2000,
        doi: '10.1234/test',
        plannedUse: 'prueba',
        limitations: 'prueba',
        verification: { status: 'candidate', verifiedOn: null, scope: 'ninguna' },
        license: { reviewed: false, redistribution: 'unknown', summary: 'no revisada' },
      },
    ],
    contexts: [
      {
        id: 'ctx.schematic_a',
        label: { es: 'Esquema A' },
        kind: 'schematic',
        species: { scope: 'species', scientificName: 'Testus a', ncbiTaxon: null },
        developmentalStage: 'adulto',
        preparation: 'no_aplica',
        modality: 'esquema',
        atlas: null,
        description: { es: 'test' },
      },
      {
        id: 'ctx.schematic_b',
        label: { es: 'Esquema B' },
        kind: 'schematic',
        species: { scope: 'species', scientificName: 'Testus b', ncbiTaxon: null },
        developmentalStage: 'adulto',
        preparation: 'no_aplica',
        modality: 'esquema',
        atlas: null,
        description: { es: 'test' },
      },
    ],
    entities: [
      {
        id: 'ent.a1',
        type: 'structure',
        semanticScale: 'pathway',
        label: { es: 'Núcleo Á', en: 'Nucleus A' },
        synonyms: [{ text: 'NA', lang: 'es' }],
        taxonScope: { kind: 'species', scientificName: 'Testus a' },
        status: 'draft',
      },
      {
        id: 'ent.a2',
        type: 'structure',
        semanticScale: 'pathway',
        label: { es: 'Corteza A' },
        taxonScope: { kind: 'species', scientificName: 'Testus a' },
        status: 'draft',
      },
      {
        id: 'ent.b1',
        type: 'structure',
        semanticScale: 'pathway',
        label: { es: 'Núcleo B' },
        taxonScope: { kind: 'species', scientificName: 'Testus b' },
        status: 'draft',
      },
    ],
    relations: [
      {
        id: 'rel.a1_to_a2',
        version: 1,
        type: 'projects_to',
        subjectId: 'ent.a1',
        objectId: 'ent.a2',
        contextId: 'ctx.schematic_a',
        claimIds: ['claim.a1_to_a2'],
        connection: {
          modality: 'pending_extraction',
          directed: true,
          sign: 'unknown',
          weight: null,
        },
        status: 'draft',
      },
    ],
    claims: [
      {
        id: 'claim.a1_to_a2',
        version: 1,
        proposition: { es: 'A1 proyecta a A2.' },
        kind: 'observation',
        subjectIds: ['ent.a1'],
        predicate: 'projects_to',
        object: { type: 'entity', id: 'ent.a2' },
        contextId: 'ctx.schematic_a',
        measurement: 'pending_extraction',
        modelId: null,
        evidence: [
          {
            sourceId: 'src.test',
            locator: 'pending',
            locatorVerified: false,
            relation: 'supports',
            methodLimitations: 'n/a',
          },
        ],
        uncertainty: {
          measurement: 'n/a',
          samplingGeneralization: 'n/a',
          competingExplanations: 'n/a',
        },
        status: 'draft',
        provenance: { author: 't', extractor: 'humano:t', createdOn: '2026-10-04', method: 't' },
        display: { label: 'observation' },
      },
      {
        id: 'claim.bridge_a_b',
        version: 1,
        proposition: { es: 'Puente conceptual A→B.' },
        kind: 'didactic_bridge',
        subjectIds: ['scene.a', 'scene.b'],
        predicate: 'conceptual_bridge_to',
        object: { type: 'entity', id: 'scene.b' },
        contextId: 'ctx.schematic_a',
        measurement: 'not_applicable',
        modelId: null,
        evidence: [],
        uncertainty: {
          measurement: 'n/a',
          samplingGeneralization: 'n/a',
          competingExplanations: 'n/a',
        },
        status: 'draft',
        provenance: { author: 't', extractor: 'humano:t', createdOn: '2026-10-04', method: 't' },
        display: { label: 'educational_schematic' },
      },
    ],
    assets: [
      {
        id: 'asset.geom_a',
        title: { es: 'Geometría A' },
        kind: 'schematic_geometry',
        nature: 'schematic',
        origin: 'project_original',
        status: 'available',
        file: { path: 'a.schematic.json', format: 'schematic+json' },
        license: {
          status: 'project_original',
          spdx: null,
          holder: null,
          attribution: null,
          redistribution: 'allowed',
          url: null,
          verifiedOn: null,
        },
        units: 'arbitrary',
        coordinateFrameId: 'frame.a',
      },
      {
        id: 'asset.geom_b',
        title: { es: 'Geometría B' },
        kind: 'mesh',
        nature: 'reconstruction',
        origin: 'external',
        status: 'blocked_missing',
        file: null,
        license: {
          status: 'pending',
          spdx: null,
          holder: null,
          attribution: null,
          redistribution: 'unknown',
          url: null,
          verifiedOn: null,
        },
        units: 'mm',
        coordinateFrameId: 'frame.b',
        blocked: { reason: { es: 'Falta' }, workPackage: 'WP-001' },
      },
    ],
    representations: [
      {
        id: 'rep.a',
        label: { es: 'Rep A' },
        contextId: 'ctx.schematic_a',
        assetId: 'asset.geom_a',
        description: { es: 'test' },
      },
      {
        id: 'rep.b',
        label: { es: 'Rep B' },
        contextId: 'ctx.schematic_b',
        assetId: 'asset.geom_a',
        description: { es: 'test' },
      },
    ],
    scenes: [
      {
        schemaVersion: '1',
        sceneId: 'scene.a',
        title: { es: 'Escena A' },
        summary: { es: 'A' },
        contextId: 'ctx.schematic_a',
        semanticScale: 'pathway',
        coordinateFrame: { kind: 'schematic', id: 'frame.a', units: 'arbitrary', axes: 'x' },
        layers: [
          {
            id: 'structures',
            label: { es: 'Estructuras' },
            kind: 'schematic',
            representationId: 'rep.a',
            entityIds: ['ent.a1', 'ent.a2'],
            evidenceClaimIds: ['claim.a1_to_a2'],
            defaultVisible: true,
          },
        ],
        transitions: [
          {
            targetSceneId: 'scene.b',
            label: { es: 'Ir a B' },
            bridgeClaimId: 'claim.bridge_a_b',
            correspondence: 'conceptual',
            contextChanges: ['species'],
          },
        ],
      },
      {
        schemaVersion: '1',
        sceneId: 'scene.b',
        title: { es: 'Escena B' },
        summary: { es: 'B' },
        contextId: 'ctx.schematic_b',
        semanticScale: 'circuit',
        coordinateFrame: { kind: 'schematic', id: 'frame.b', units: 'arbitrary', axes: 'x' },
        layers: [
          {
            id: 'structures',
            label: { es: 'Estructuras' },
            kind: 'schematic',
            representationId: 'rep.b',
            entityIds: ['ent.b1'],
            defaultVisible: true,
          },
        ],
      },
    ],
    lessons: [
      {
        schemaVersion: '1',
        lessonId: 'lesson.a',
        title: { es: 'Lección' },
        audience: 'test',
        durationMinutes: 5,
        objectives: [{ es: 'Objetivo' }],
        status: 'draft',
        steps: [
          {
            id: 'one',
            sceneId: 'scene.a',
            title: { es: 'Uno' },
            narrative: { es: 'Observa.' },
            claimIds: ['claim.a1_to_a2'],
            focusEntityIds: ['ent.a1'],
            visibleLayerIds: ['structures'],
          },
          {
            id: 'two',
            sceneId: 'scene.b',
            title: { es: 'Dos' },
            narrative: { es: 'Compara.' },
            focusEntityIds: ['ent.b1'],
          },
        ],
      },
    ],
    models: [],
  });
}

export function makeFixtureGeometry(): Map<string, SchematicGeometry> {
  return new Map([
    [
      'asset.geom_a',
      SchematicGeometry.parse({
        schemaVersion: '1',
        assetId: 'asset.geom_a',
        frame: { units: 'arbitrary', axes: 'x' },
        disclaimer: { es: 'Esquema' },
        nodes: [
          {
            id: 'a1',
            entityId: 'ent.a1',
            shape: 'sphere',
            position: [0, 0, 0],
            size: [1, 1, 1],
            side: 'none',
            group: 'g',
          },
          {
            id: 'a2',
            entityId: 'ent.a2',
            shape: 'sphere',
            position: [1, 0, 0],
            size: [1, 1, 1],
            side: 'none',
            group: 'g',
          },
          {
            id: 'b1',
            entityId: 'ent.b1',
            shape: 'sphere',
            position: [2, 0, 0],
            size: [1, 1, 1],
            side: 'none',
            group: 'g',
          },
        ],
        links: [],
      }),
    ],
  ]);
}
